name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Compilar PDF e fazer upload como artefato
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          lfs: true
      
      - name: Compilar documento LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: principal.tex
      
      - name: Fazer upload do Artefato
        uses: actions/upload-artifact@v4
        with:
          name: Documento
          path: |
            README.md
            principal.pdf

  deploy:
    name: Deploy da última versão do PDF e do README.md para a branch do gh-pages
    if: github.event_name == 'push' # only deploy on push
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Obter o PDF e o README.md dos artefatos 
        uses: actions/download-artifact@v4
        with:
          name: Documento
          path: ./public
      
      - name: Fazer commit e push do PDF e do README.md para a branch do gh-pages
        run: |
          cd public
          git init -b temp
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit -m "[CI] Atualizar PDF e README.md para versão mais recente"
          git push --force origin temp:gh-pages
